"""Convert a short video to bounded, flash-resident HUB75 RLE frames.

Requires Python, Pillow and an ffmpeg executable. See README.md in this folder.
"""
import argparse
import hashlib
import json
import subprocess
from pathlib import Path
from PIL import Image, ImageDraw

p = argparse.ArgumentParser()
p.add_argument('source', type=Path)
p.add_argument('output', type=Path)
p.add_argument('--ffmpeg', required=True)
p.add_argument('--preview-dir', type=Path, required=True)
p.add_argument('--crop', nargs=4, type=int, metavar=('WIDTH','HEIGHT','X','Y'))
p.add_argument('--fill-panel', action='store_true')
args = p.parse_args()
fps, duration, width, height = 24, 4, 64, 32
filters = [f'fps={fps}']
if args.crop:
    assert min(args.crop[:2]) > 0 and min(args.crop[2:]) >= 0
    filters.append('crop='+':'.join(str(v) for v in args.crop))
if args.fill_panel:
    filters.extend([f'scale={width}:{height}:force_original_aspect_ratio=increase:flags=lanczos',
                    f'crop={width}:{height}:(iw-ow)/2:(ih-oh)/2'])
else:
    filters.extend([f'scale={width}:{height}:force_original_aspect_ratio=decrease:flags=lanczos',
                    f'pad={width}:{height}:(ow-iw)/2:(oh-ih)/2:color=black'])
filters.append('setsar=1')
raw = subprocess.check_output([
    args.ffmpeg, '-v', 'error', '-i', str(args.source), '-an', '-t', str(duration),
    '-vf', ','.join(filters),
    '-f', 'rawvideo', '-pix_fmt', 'rgb24', '-'])
assert len(raw) == width * height * 3 * fps * duration, 'Unexpected clip length'
frames = [Image.frombytes('RGB', (width,height), raw[i:i+width*height*3])
          for i in range(0,len(raw),width*height*3)]
atlas = Image.new('RGB', (width,height*len(frames)))
for i,frame in enumerate(frames): atlas.paste(frame,(0,i*height))
palette_image = atlas.quantize(colors=256,method=Image.Quantize.MEDIANCUT)
palette = palette_image.getpalette()[:768]
encoded, offsets, decoded = [], [0], []
for frame in frames:
    indices = frame.quantize(palette=palette_image,dither=Image.Dither.NONE)
    pixels = indices.tobytes()
    i = 0
    while i < len(pixels):
        end = i+1
        while end < len(pixels) and end-i < 255 and pixels[end] == pixels[i]: end += 1
        encoded.extend((end-i,pixels[i])); i = end
    offsets.append(len(encoded)); decoded.append(indices.convert('RGB'))

def array(name, ctype, values):
    lines = [', '.join(str(v) for v in values[i:i+24]) for i in range(0,len(values),24)]
    return f'static const {ctype} {name}[] PROGMEM = {{\n    '+',\n    '.join(lines)+'\n};\n'

header = '''// Generated by tools/startup/convert_startup.py; do not edit frame data manually.
// Valve Steam Deck default boot animation, as requested: https://youtu.be/ms7Eq_bh2Tc
// Visual asset belongs to Valve; no audio is embedded.
#pragma once
#include <stdint.h>
namespace StartupClip {
static constexpr uint16_t kWidth = 64, kHeight = 32, kPixelCount = 2048;
static constexpr uint16_t kFrameCount = 96, kFramesPerSecond = 24;
static constexpr uint32_t kDurationMs = 4000;
'''
header += array('kPalette','uint8_t',palette)
header += array('kOffsets','uint32_t',offsets)
header += array('kData','uint8_t',encoded) + '}\n'
args.output.parent.mkdir(parents=True,exist_ok=True)
args.output.write_text(header,encoding='utf-8')
args.preview_dir.mkdir(parents=True,exist_ok=True)
previews = [im.resize((512,256),Image.Resampling.NEAREST) for im in decoded]
# GIF timestamps approximate 24 FPS; the firmware uses exact millisecond timestamps.
previews[0].save(args.preview_dir/'startup-preview.gif',save_all=True,append_images=previews[1:],
                 duration=[40,40,50]*32,loop=0,optimize=False)
sheet = Image.new('RGB',(512*4,280*2),'#181818')
draw = ImageDraw.Draw(sheet)
for n,idx in enumerate(range(0,96,12)):
    x,y=(n%4)*512,(n//4)*280
    sheet.paste(previews[idx],(x,y)); draw.text((x+8,y+260),f'{idx/fps:.1f}s',fill='white')
sheet.save(args.preview_dir/'startup-preview.png')
errors = [abs(a-b) for original,converted in zip(frames,decoded)
          for a,b in zip(original.tobytes(),converted.tobytes())]
manifest = {
    'reference_url':'https://youtu.be/ms7Eq_bh2Tc',
    'source':'Valve Steam client steamui/movies/deck_startup.webm (local installed asset)',
    'source_sha256':hashlib.sha256(args.source.read_bytes()).hexdigest(),
    'owner':'Valve', 'audio_embedded':False, 'width':width, 'height':height,
    'fps':fps, 'frames':len(frames), 'duration_ms':duration*1000,
    'rle_bytes':len(encoded), 'palette_bytes':len(palette), 'offset_bytes':len(offsets)*4,
    'decoded_sha256':[hashlib.sha256(im.tobytes()).hexdigest() for im in decoded],
    'rgb_quantization_mean_absolute_error':sum(errors)/len(errors),
    'rgb_quantization_max_error':max(errors),
    'generated_header_sha256':hashlib.sha256(args.output.read_bytes()).hexdigest(),
    'source_crop_whxy':args.crop,
    'panel_fit':('Fill each 64x32 panel, preserving proportions and cropping outer edges'
                 if args.fill_panel else 'Aspect ratio preserved, centered on each 64x32 panel')
}
(args.preview_dir/'startup-asset.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
print(json.dumps({k:v for k,v in manifest.items() if k != 'decoded_sha256'},indent=2))
